# Generated by Django 3.1.3 on 2020-11-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast', models.CharField(max_length=30000)),
                ('date', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'forecasts',
            },
        ),
    ]
