# Generated by Django 3.1.3 on 2020-11-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='date',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast',
            field=models.CharField(default='None', max_length=30000),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='location',
            field=models.CharField(default='cosna', max_length=20),
        ),
    ]
