# Generated by Django 3.1.3 on 2020-11-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20201123_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='location',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
