# Generated by Django 3.1.3 on 2020-12-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20201130_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='cosna', max_length=10)),
                ('frequency', models.CharField(default='1', max_length=20)),
                ('hour', models.CharField(default='08h00', max_length=20)),
            ],
        ),
    ]
