# Generated by Django 3.1.3 on 2020-12-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='alarm_status',
            field=models.CharField(default='off', max_length=4),
        ),
    ]
