# Generated by Django 3.1.3 on 2020-12-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20201203_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='frequency',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='hour',
            field=models.CharField(default='5', max_length=20),
        ),
    ]
