# Generated by Django 3.1.3 on 2020-12-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_auto_20201205_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='frequency',
            new_name='day',
        ),
    ]
